### ISSUE TITLE
Upgrading to v0.4.0 resulted in Function `...` not found in environment `production`. It may exist other environments, you may need to overwrite the environment while deploying to `production`.

### ISSUE THREAD

**Issue by benholmen** [hammerstonedev/sidecar#108]
I ran into this today after upgrading to version 0.4.0 and the solution was pretty straightforward. Sharing here in case anyone is googling for the same issue!

The [0.4.0 release](https://github.com/hammerstonedev/sidecar/releases/tag/v0.4.0) includes a breaking change to how Lambda functions are named. In our case, even though our environment was the same, our function name changed from `SC-Project-browsershot` -> `sc-project-browsershot` which did not exist yet.

Resolving it was trivial, re-deploying and re-activating created a function with the updated function name. If you are deploying and activating in your build pipeline this will be a non-issue for you; we were not (until today) so it bit us.

```shell
php artisan sidecar:deploy --env=production
php artisan sidecar:activate --env=production
```

After re-deplying, here's how our Lambda dashboard looks:

![image](https://user-images.githubusercontent.com/1056188/228621445-6e729bd8-680d-42f6-80ee-6356c16ea369.png)

Thanks @aarondfrancis for the explanation!

**Comment by aarondfrancis** [comment]
Going to close this since there's nothing to do, but thanks @benholmen for opening it so people searching might find it!
