### ISSUE TITLE
Undefined array key 0 on sidecar:configure

### ISSUE THREAD

**Issue by antergos98** [hammerstonedev/sidecar#11]
Here is the error message:

![image](https://user-images.githubusercontent.com/46461380/119421117-f9c8c700-bccb-11eb-8fc2-036d5716359f.png)

**Comment by aarondfrancis** [comment]
You're a legend. Gimme a bit

**Comment by aarondfrancis** [comment]
Couldn't reproduce, but added safe array access. Thanks for reporting!

**Comment by antergos98** [comment]
@aarondfrancis it's working. Thank you very much for your quick fixes :)
