### ISSUE TITLE
Container Handlers: Force redeploy if the container is updated

### ISSUE THREAD

**Issue by ianrothmann** [hammerstonedev/sidecar#121]
Hi there,

Thanks for the wonderful package. It really saves lives 😎

I have a use case where I use a container and so in my handler function, I return Package::CONTAINER_HANDLER;

The page contains the ImageUrl with tag :latest.

It happens that the container code gets updated, but sidecar refuses to redeploy because of the below code in LambdaHandler.php (line 143 - I commented this line). This is because the ImageUri is still exactly the same, but the container has been updated.

![Screenshot 2023-05-09 at 17 28 13](https://github.com/hammerstonedev/sidecar/assets/4319223/2e6a6a8c-7c63-4587-acb8-47e456f9441c)

Would it be possible that we can add a flag to the command to force a redeploy?

Kind regards,

Ian

**Comment by aarondfrancis** [comment]
Thanks for opening an issue! Is this the same as this issue: https://github.com/hammerstonedev/sidecar/issues/67.

If so, can you think of a generalized solution that would work? I don't deploy containers so I'll admit I'm not _fully_ up to speed on their workings, but I would like to fix this.

**Comment by ianrothmann** [comment]
Indeed it does work. I did:

```
public function package()
    {
        return [
            'ImageUri' => '...:latest',
            '__handler__' => rand(1,10000), //Ensuring that the package updates
        ];
    }
```

Thanks for your help!
