### ISSUE TITLE
Latest Laravel version v10.21 not supported

### ISSUE THREAD

**Issue by ssatz** [hammerstonedev/sidecar#128]
Need to upgrade the psr/http-message  version to 2

**Comment by w00key** [comment]
I just stumbled on this, I think its laravel asking for v1 or v2 of http-message, so you get version 2. Then sidecar is asking for version 2 of maennchen/zipstream-php which only asks for v1 which it won't rollback for.

If you add 

"psr/http-message": "^1.0"

to your laravel composer file and run composer update it will downgrade the package as laravel still supports this.

This is a temporary fix as the main fix should be to bump to v3 of maennchen/zipstream-php which uses v2 of http-message.

**Comment by ssatz** [comment]
@w00key Thanks! I did exactly

**Comment by njoguamos** [comment]
@w00key Thank you.

**Comment by aarondfrancis** [comment]
Should be updated!
