### ISSUE TITLE
Lambda deprecating Node.js 14.x runtime

### ISSUE THREAD

**Issue by wilsenhc** [hammerstonedev/sidecar#135]
According to the AWS Lambda Supported Runtimes, Node.js 14.x runtime will be **deprecated starting Nov 27, 2023**, in Phase 1 deprecation which means the following: 

> Phase 1 - Lambda no longer applies security patches or other updates to the runtime. **You can no longer create functions that use the runtime**, but you can continue to update existing functions. This includes updating the runtime, and rolling back to the previous runtime. Note that functions that use a deprecated runtime are no longer eligible for technical support.

This means new functions can not be created using Node.js 14.x which is the [default runtime](https://github.com/hammerstonedev/sidecar/blob/main/src/LambdaFunction.php#L234) in the base LambdaFunction of this package.

**Comment by aarondfrancis** [comment]
Pushed a change for that. Thank you!
