### ISSUE TITLE
Error executing "ListVersionsByFunction": Environment name repeated twice in lambda name

### ISSUE THREAD

**Issue by 60days** [hammerstonedev/sidecar#19]
Hi - I'm sure I'm doing something wrong, but not quite sure what. I've been writing/testing lambdas locally successfully, and I'm now attempting to push to my staging env.

The CI flow is a github action (PHP based) that runs the vapor deploy staging command, then the deploy/activate divided between build & deploy stages as suggested in the docs.

The error I get at the 'activate' stage is:

```
Error executing "ListVersionsByFunction" on "https://lambda.***.  
  amazonaws.com/2015-03-31/functions/SC-Variant-Staging-staging-Sidecar-Sharp  
  ResizeImageLambda/versions?MaxItems=100"; AWS HTTP error: Client error: `GE  
  T https://lambda.***.amazonaws.com/2015-03-31/functions/SC-Varia  
  nt-Staging-staging-Sidecar-SharpResizeImageLambda/versions?MaxItems=100` re  
  sulted in a `404 Not Found
```

Looking at the lambdas deployed, I can see why the 404 occurs, as the only deployed staging version is 'SC-Variant-staging-Sidecar-SharpResizeImageLambda' (note the single, lowercase 'staging').

**Comment by aarondfrancis** [comment]
Hmm... Is your APP_NAME different in staging? perhaps `Varitan Staging`. I ask because I don't _think_ I capitalize the env ever, so it may be coming from somewhere else.

Lemme know!

**Comment by 60days** [comment]
That was it! I was wracking my brains trying to think all the places the name could come from, but was focusing on the vapor build process. Thanks for the help & the package itself!

**Comment by aarondfrancis** [comment]
No worries! That's a new one for me, I'll add it to the docs. You won't be
the only one with that setup I'm sure.
