### ISSUE TITLE
Deleted Lambdas, cannot deploy anymore

### ISSUE THREAD

**Issue by maurocasas** [hammerstonedev/sidecar#23]
Hey there!

Most amazing package in a long time.. but cannot seem to debug what I've done wrong.
I've had 2 functions and deleted them from my AWS to deploy fresh, and because I was getting really long delays on deploy when it's usually seconds..

I am now getting this error 

```
Error executing "Invoke" on "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/SC-E-local-Sidecar-Zoom-EnableCustomLivestreaming%3Aactive/invocations"; AWS HTTP error: Client error: `POST https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/SC-E-local-Sidecar-Zoom-EnableCustomLivestreaming%3Aactive/invocations` resulted in a `404 Not Found` response:
{"Message":"Function not found: arn:aws:lambda:us-east-1:11111:function:SC-E-local-Sidecar-Zoom-EnableCustom (truncated...)
 ResourceNotFoundException (client): Function not found: arn:aws:lambda:us-east-1:111111:function:SC-E-local-Sidecar-Zoom-EnableCustomLivestreaming:active - {"Message":"Function not found: arn:aws:lambda:us-east-1:11111111:function:SC-E-local-Sidecar-Zoom-EnableCustomLivestreaming:active","Type":"User"}
```

Any idea how I can "clear" this issue?

Thanks again!

**Comment by maurocasas** [comment]
For anyone who comes here, I had made a very silly mistake. You should never have this issue like me.

**Comment by aarondfrancis** [comment]
Ha @maurocasas I've definitely been there!

Is there anything I should add to prevent others from making the mistake, or are we all good here?

**Comment by maurocasas** [comment]
All good. I had a snippet of "note taking" in my code which was invoking the script itself.. nothing realistic

**Comment by aarondfrancis** [comment]
🙈 

Thanks for reporting back! And let me know if I can do anything to help in the future!
