### ISSUE TITLE
Laravel 9 Support? 

### ISSUE THREAD

**Issue by njames** [hammerstonedev/sidecar#53]
I have created a PR to add L9 support. 

I feel it is a bit naive but I didn't want to point out a problem without having a go at the solution. 

Use or discard at your discretion. 

Cheers.

**Comment by njames** [comment]
Yes @d8vjork  - I saw that after I submitted. I looked in issues first and not PR's, mistakenly thinking that someone would have raised an issue first. 

Either way you are right  - hope L9 support is merged in soon :)

**Comment by aarondfrancis** [comment]
Merged in #50! Thanks yall for all your help!
