### ISSUE TITLE
[ASK] Using AWS Lambda Layers upon deployment

### ISSUE THREAD

**Issue by kevinpurwito** [hammerstonedev/sidecar#57]
Hi, how do I configure AWS Lambda Layers? 

I've added the layer manually in the Lambda function, but it always get emptied on each deployment (`php artisan sidecar:deploy`).

I've read the docs & source dive, but still couldn't figure it out.

Is it at least possible to deploy the changes in the code only, without emptying the Layers that I've set manually?

Thank you very much for this awesome package btw!

**Comment by aarondfrancis** [comment]
I think if you set *anything* manually Sidecar will clobber it. Are you setting it manually in the AWS console? The best way to use a layer is with the `layers` method on your `LambdaFunction` class.

**Comment by kevinpurwito** [comment]
Hi, thanks for the reply! I see so I just need to put the ARN of the layer I'm going to use. Will try it.

Thanks again!

**Comment by kevinpurwito** [comment]
I can confirm that the `layers` works, thank you.
