### ISSUE TITLE
SettledResult::parseLogs does not handle multi-line log entries

### ISSUE THREAD

**Issue by inxilpro** [hammerstonedev/sidecar#65]
If my sidecar function calls:

```js
console.log(`Result: ${ JSON.stringify(result, null, 2) }`);
```

Then `parseInfoLine` fails on line 262:
https://github.com/hammerstonedev/sidecar/blob/651381a336a2a54a3274abed341ee70a74136402/src/Results/SettledResult.php#L252-L262

I honestly don't have a great solution for this right now—if I come up with something I'll submit a PR. For others who are running into this issue, the solution for now is to just avoid any multi-line log entries.

**Comment by aarondfrancis** [comment]
Thanks mod-man Chris. Fixed with #66. 

Logging needs to be re-thought, but I'll do that later!
