### ISSUE TITLE
Call to undefined method Hammerstone\Sidecar\Commands\Actions\DetermineRegion::choice()

### ISSUE THREAD

**Issue by antergos98** [hammerstonedev/sidecar#7]
I have this error when I use the sidecar:configure command:

![image](https://user-images.githubusercontent.com/46461380/119291683-db57c280-bc1c-11eb-91ec-c08a481538f7.png)

Looks like the `choice` methods doesn't exist in neither `DetermineRegion ` or `BaseAction` class.

**Comment by aarondfrancis** [comment]
Thanks for reporting @antergos98. I have pushed a fix and published `0.1.1`. That should fix it!
