### ISSUE TITLE
Infinite activation on Laravel Vapor

### ISSUE THREAD

**Issue by jeffreyvanhees** [hammerstonedev/sidecar#74]
Hi @aarondfrancis!

Something strange occurs when the activate command is running during a deployment in Laravel Vapor. When I run this command locally, it's super fast, but on Vapor it hangs infinite till the process is killed after a couple of minutes. Also with forcing the production environment locally, everything goes fine.

![Screenshot 2022-06-17 at 17 14 42](https://user-images.githubusercontent.com/8754630/174328522-6389c4bb-d70b-41d8-b476-8db2d9f66267.png)

My `vapor.yaml` is like:
```
build:
 - ...
 - 'php artisan sidecar:deploy --env=production'
deploy:
 - ...
 - 'php artisan sidecar:activate --env=production'
```

Laravel Vapor does not show any errors but the deployment just 'fails'. They only thing AWS Cloudwatch tells me in the vapor-production-cli-log is:
```Fatal error: Uncaught Symfony\Component\Process\Exception\ProcessSignaledException: The process has been signaled with signal "11". in /var/task/vendor/symfony/process/Process.php:434```

Any idea what I'm doing wrong or where else I can look? Or did I just find a bug?

Thanks!

Jeffrey

**Comment by aarondfrancis** [comment]
Hmm that's not something I've seen before! Is it still ongoing or is it transient? It's entirely possible it was a AWS thing.

**Comment by jeffreyvanhees** [comment]
Hmm, I've tested it again today and unfortunately the same problem. I'll take a better look and try to figure it out, but it look like it isn't something at AWS.

**Comment by aarondfrancis** [comment]
Can you view the output of the activate step and see if it's hung up or failing on a particular function?

<img width="811" alt="image" src="https://user-images.githubusercontent.com/881931/180814312-66d840b2-e34b-4f89-87ea-766e1b487405.png">

**Comment by jeffreyvanhees** [comment]
> Can you view the output of the activate step and see if it's hung up or failing on a particular function?
> 
> <img alt="image" width="811" src="https://user-images.githubusercontent.com/881931/180814312-66d840b2-e34b-4f89-87ea-766e1b487405.png">

Hi @aarondfrancis, sorry I didn't notice you already replied. The output was completely empty. 

I tried it again today and suddenly, you guessed it, everything works as expected. I have no idea what the problem was but perhaps it had nothing to do with Sidecar and/or Vapor.
