### ISSUE TITLE
Support pipes in app name when creating function name

### ISSUE THREAD

**Issue by bennyvdhoogen** [hammerstonedev/sidecar#75]
In addition to this already closed issue: https://github.com/hammerstonedev/sidecar/issues/20, using a pipe (eg. `APP_NAME="Vriend van de Show | Local"`) also breaks the creation of AWS Lambda functions.

**Comment by vriendvandeshow** [comment]
Also related to the following open PR: https://github.com/hammerstonedev/sidecar/pull/30

**Comment by aarondfrancis** [comment]
Just fixed this with pr #30. Will cut a new (breaking) release soon! Thanks for opening the issue.
