### ISSUE TITLE
Allow for tagging

### ISSUE THREAD

**Issue by bryanjamesmiller** [hammerstonedev/sidecar#78]
We have a requirement to add tagging (AWS tags) to sort of label our lambda functions.  I think this is mostly for billing purposes, as different teams create lambdas and the bill needs to go to different places even though it's one big AWS account, but it might be useful to have tagging for other purposes as well.

**Comment by wilsenhc** [comment]
Just opened a PR to add this functionality. Hope it fits your team/project(s) 👍🏻

See #86
