### ISSUE TITLE
Support for Cloudflare Workers

### ISSUE THREAD

**Issue by fieu** [hammerstonedev/sidecar#85]
I'm not sure if this is on the roadmap or what, though considering you support Lambda and [Cloudflare Workers](https://workers.cloudflare.com/) is doing the same thing in JS/Rust, I think it could be a good addition to support it to provide an alternative to running code on Amazon's infrastructure.

This package is heavily Lambda dependent and wasn't made to support multiple providers.

Would a PR to support Cloudflare Workers be accepted or is the scope of this package set on AWS Lambda only?

**Comment by wilsenhc** [comment]
Aaron already has some work in progress about building support for Vercel Functions (#64) so that's a good sign that this could/would support multiple serverless providers in the future.

I think #64 could be a good starting point for you to implement a PR for Cloudflare Workers

**Comment by fieu** [comment]
Understood, thanks for the reply.
