### ISSUE TITLE
Error executing "HeadBucket" on "https://s3.ca-central-1.amazonaws.com/sidecar-";

### ISSUE THREAD

**Issue by antergos98** [hammerstonedev/sidecar#9]
The configure commands requires me to have `SIDECAR_ARTIFACT_BUCKET_NAME` defined in my .env, otherwise it won't work.

![image](https://user-images.githubusercontent.com/46461380/119359817-015e8080-bc78-11eb-8fce-15dd03a1e1cc.png)

**Comment by aarondfrancis** [comment]
@antergos98 this is valuable feedback! Gimme a few minutes

**Comment by aarondfrancis** [comment]
Fixed! Thanks for reporting.

**Comment by antergos98** [comment]
Thanks for fixing :)
