### ISSUE TITLE
Method Illuminate\Support\Str::replace does not exist on Laravel 7

### ISSUE THREAD

**Issue by RicardoRamirezR** [hammerstonedev/sidecar#91]
Deploying sidecar on Laravel 7 throws this error

**Comment by aarondfrancis** [comment]
Ah, good catch! Can you show me the stack trace?

**Comment by RicardoRamirezR** [comment]
This what I got:

<img width="1376" alt="Captura de Pantalla 2022-10-14 a la(s) 4 03 44 p m" src="https://user-images.githubusercontent.com/6526545/195943703-ece34aa3-6016-430c-bfd5-7311682ba599.png">

**Comment by aarondfrancis** [comment]
Dropped support for Laravel 7
